### ISSUE TITLE
Please fix lack of documentation and remove confusing sample plugin docs in README

### ISSUE THREAD

**Issue by daaain** [eharris128/Obsidian-LLM-Plugin#131]
I'm looking for a plugin that would enable me to use a local LLM to do various tasks with my notes (like iteratively chatting over some ideas with a single note in context) and this plugin looks like it has some recent momentum, but for a few minutes I was really confused by the README until I realised it's just the unedited sample plugin one.

I still have no idea what this plugin does and how to use it though, so even if the functionality is in flux, it would be great if there was at least some provisional documentation about how to get started with it.

**Comment by r-mahoney** [comment]
Sorry about that. Since we haven't pushed a public release yet, this has been something that's fallen to the wayside. Ill go ahead and update it so it at least makes sense if anyone wants to play around with it.

**Comment by r-mahoney** [comment]
Updated the README so it's hopefully easier to install and use this plugin. It sounds like what you want to get out of this plugin is accomplished through the use of the Local Docs function of GPT4All models. We don't currently have an implementation for chatting about notes with OpenAI models, but I know that there is a way to do this with their assistants feature and we have plans to add access to assistants at some point in the future, so this is on our radar.

Feel free to reach out if you have any other comments or concerns

**Comment by r-mahoney** [comment]
Just wanted to reach out and let you know that I added a file search feature that should support your use case. It's very much in beta right now, but wanted to let you know since it was something you specifically mentioned.

To work with it you just need to update/install with BRAT then there should be a Robot Icon in the header of any view you use (Modal, FAB, or Widget) that will allow you to create an OpenAI assistant and select the file or files you want to attach to that assistant. Right now adding files is a little tedious, you have to manually type, or copy and paste, the file name into the text box followed by ".md" 
 - So a file called "Daily Planning" should be typed in as "Daily Planning.md"
Then the assistant will show up in the list of models in the view settings and you should be able to interact with it after that.
